
services:
  mongo:
    image: mongo:7
    container_name: morrochat-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: morrochat
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  chromadb:
    image: chromadb/chroma:latest
    container_name: morrochat-chromadb
    restart: unless-stopped
    environment:
      IS_PERSISTENT: 'TRUE'
      PERSIST_DIRECTORY: /chroma/.chroma/index
      CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER: 'chromadb.auth.providers.NoAuthServerProvider'
    ports:
      - '8000:8000'
    volumes:
      - chroma_data:/chroma/.chroma/index

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: morrochat-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/morrochat?authSource=admin
      NODE_ENV: production
      CHROMA_URL: http://chromadb:8000
    depends_on:
      - mongo
      - chromadb
      - searxng
    ports:
      - '3000:3000'

  searxng:
    image: searxng/searxng:latest
    container_name: morrochat-searxng
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - "8888:8080"
    environment:
      - SEARXNG_BASEURL=http://localhost:8888/
      - INSTANCE_NAME="morrochat-searxng"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: morrochat-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  mongo_data:
  chroma_data:
  searxng_data:
