
services:
  mongo:
    image: mongo:7
    container_name: morrochat-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: morrochat
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - morrochat-network

  redis:
    image: redis:7-alpine
    container_name: morrochat-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - morrochat-network

  tor:
    image: dperson/torproxy
    container_name: morrochat-tor
    restart: unless-stopped
    environment:
      - TOR_MaxCircuitDirtiness=60
      - TOR_NewCircuitPeriod=30
      - TOR_MaxCircuitDirtiness=600
      - TZ=UTC
    expose:
      - "8118" # HTTP proxy
      - "9050" # SOCKS5 proxy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8118 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - morrochat-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: morrochat-chromadb
    restart: unless-stopped
    environment:
      IS_PERSISTENT: 'TRUE'
      PERSIST_DIRECTORY: /chroma/.chroma/index
      CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER: 'chromadb.auth.providers.NoAuthServerProvider'
    ports:
      - '8000:8000'
    volumes:
      - chroma_data:/chroma/.chroma/index
    networks:
      - morrochat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: morrochat-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/morrochat?authSource=admin
      NODE_ENV: production
      CHROMA_URL: http://chromadb:8000
      SEARXNG_BASE_URL: http://searxng:8080
    depends_on:
      - mongo
      - chromadb
      - searxng
    ports:
      - '3000:3000'
    networks:
      - morrochat-network

  searxng:
    image: searxng/searxng:latest
    container_name: morrochat-searxng
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - "8888:8080"
    environment:
      - SEARXNG_BASEURL=http://searxng:8080/
      - INSTANCE_NAME=morrochat-searxng
      - SEARXNG_HOSTNAME=0.0.0.0
      - SEARXNG_REQUEST_TIMEOUT=60
      - SEARXNG_CONNECT_TIMEOUT=30
      - SEARXNG_RESULTS_PER_PAGE=10
      - SEARXNG_LIMITER=false
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - SEARXNG_OUTGOING_HTTP_PROXY=http://tor:8118
      - SEARXNG_OUTGOING_HTTPS_PROXY=http://tor:8118
      - http_proxy=http://tor:8118
      - https_proxy=http://tor:8118
      - no_proxy=localhost,127.0.0.1
    depends_on:
      redis:
        condition: service_started
      tor:
        condition: service_healthy
    networks:
      - morrochat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: morrochat-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - morrochat-network

networks:
  morrochat-network:
    driver: bridge

volumes:
  mongo_data:
  chroma_data:
  redis_data:
  searxng_data:
